### ISSUE TITLE
Programm crashed 

### ISSUE THREAD

**Issue by hohland-18** [SnakeSolid/rust-no-dpi-socks#1]
Hello, i compiled your programm for my router(MIPS32) and when connect from my browser i got error:

thread 'tokio-runtime-worker' panicked at src/transfer.rs:51:35:
chunk size must be non-zero

Is it possible to fix this somehow?

**Comment by SnakeSolid** [comment]
Bug fixed in master. Please, try to run last version.

**Comment by hohland-18** [comment]
Works fine, thanks!
